name: Publish Docker Images

on:
  push:
    branches:
    - stable
    - dev

jobs:
  push_to_registry:
    name: Push Docker images to Dockerhub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Publish aflpp ${{ github.ref }} to Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: aflplusplus/aflplusplus:${{ github.ref }}
      if: "${{ github.ref }}" == "dev"
    - name: Publish aflpp ${{ github.ref }} and latest to Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: aflplusplus/aflplusplus:${{ github.ref }},aflplusplus/aflplusplus:latest
      if: "${{ github.ref }}" == "stable"
