name: CI

on:
  push:
    branches: [ stable, dev ]
  pull_request:
    branches: [ stable, dev ]

jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - name: debug:
        run: apt-cache search plugin-dev | grep gcc ; apt-cache search clang | grep clang-
      - name: install packages
        run: sudo apt-get install -y -m -f --install-suggests build-essential git libtool libtool-bin automake bison libglib2.0-0 clang llvm-dev libc++-dev findutils libcmocka-dev python3-dev python3-setuptools
      - name: compiler installed
        run: gcc -v ; clang -v
      - name: build afl++
        run: make distrib ASAN_BUILD=1
      - name: run tests
        run: sudo -E ./afl-system-config ; sudo sysctl -w kernel.shmmax=10000000000 ; export AFL_SKIP_CPUFREQ=1 ; make tests
