name: C/C++ CI

on:
  push:
    branches: [ stable, dev ]
  pull_request:
    branches: [ stable, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make tests
      run: make tests
